# -*- coding: utf-8 -*-
"""
tests/test_adversarial_m1_stress.py — Adversarial Stress Test Suite for Milestone 1
Generated by challenger_m1_2 (critic & specialist)

Covers 3 critical challenge areas:
1. Social Visibility & Post Formatting Stress:
   - All compact_post_icon variations across sets, head, and face items.
   - Extreme custom prefixes, long names (up to 5,000 chars), adversarial HTML injection.
   - Verification of Telegram 4096 / 1024 bounds and HTML parsing without entity corruption.
2. Work Engine 16 Shifts & hat_helmet Zero Fine Perk:
   - Exhaustive verification across all 16 career vacancies.
   - hat_helmet zero fine guarantee under worst-case random fail rolls (risk_pct forced to trigger).
   - Zero division stress testing with boundary numbers, gear combinations, and multipliers.
3. Combat Moderation Engine High Volume Calls:
   - 10,000+ high-volume executions of calculate_combat_duration_and_backfire.
   - Empirical validation of mute reduction (-50% helmet, -70% riot police).
   - Statistical binomial validation of feet_sneakers evasion (30%) and body_cloak stealth (15%).
   - Expired durability enforcement under heavy attack frequency.
"""

import time
import math
import html
import random
import re
from xml.etree import ElementTree as ET
from unittest.mock import patch, MagicMock

import pytest

import wardrobe_engine
import combat_moderation_engine
from common import work_engine
from common.html_utils import escape_html
import post_helpers
import stats_generator


# =====================================================================
# 1. SOCIAL VISIBILITY & POST FORMATTING STRESS
# =====================================================================

def test_compact_post_icon_exhaustiveness():
    """Verify all set bonuses and items generate non-breaking compact_post_icon strings."""
    now = int(time.time())

    expected_set_icons = {
        "set_riot_police": "🪖 ",
        "set_anime_hikka": "🐱 ",
        "set_gop_skuf": "👑 ",
        "set_ward6": "🥼 ",
        "set_neo": "🕶️ ",
        "set_wasserman": "🦺 ",
    }
    for set_id, expected_icon in expected_set_icons.items():
        set_info = wardrobe_engine.SET_BONUSES[set_id]
        active_items = {}
        for item_id in set_info["items"]:
            slot = wardrobe_engine.CLOTHING_CATALOG[item_id]["slot"]
            active_items[f"equipped_{slot}"] = item_id
            active_items[f"{item_id}_is_permanent"] = True

        stats = wardrobe_engine.get_wardrobe_total_stats(active_items, current_time=now)
        assert stats["compact_post_icon"] == expected_icon, f"Failed for set {set_id}"
        assert isinstance(stats["compact_post_icon"], str)
        # Ensure icon is valid UTF-8 and contains no unclosed surrogate
        stats["compact_post_icon"].encode("utf-8")

    expected_head_icons = {
        "hat_tinfoil": "👽 ",
        "hat_crown": "👑 ",
        "hat_cat_ears": "🐱 ",
        "hat_helmet": "🪖 ",
        "hat_tophat": "🎩 ",
        "hat_bag": "📦 ",
    }
    for head_id, expected_icon in expected_head_icons.items():
        active_items = {
            "equipped_head": head_id,
            f"{head_id}_is_permanent": True,
        }
        stats = wardrobe_engine.get_wardrobe_total_stats(active_items, current_time=now)
        assert stats["compact_post_icon"] == expected_icon, f"Failed for head {head_id}"

    expected_face_icons = {
        "face_anon_mask": "🎭 ",
        "face_clown_nose": "🤡 ",
        "face_thug_glasses": "🕶️ ",
    }
    for face_id, expected_icon in expected_face_icons.items():
        active_items = {
            "equipped_face": face_id,
            f"{face_id}_is_permanent": True,
        }
        stats = wardrobe_engine.get_wardrobe_total_stats(active_items, current_time=now)
        assert stats["compact_post_icon"] == expected_icon, f"Failed for face {face_id}"


@pytest.mark.asyncio
async def test_post_headers_adversarial_html_and_length():
    """
    Stress-test format_header and format_thread_post_header with adversarial strings:
    - Raw HTML injections (<script>, <b unclosed, & entities, nested tags).
    - Huge strings (up to 5,000 characters).
    - Verify escape_html and delivery_manager message assembly produces valid XML/HTML.
    """
    now = int(time.time())

    adversarial_inputs = [
        "<script>alert('xss')</script>",
        "<b>bold<i>italic</s>",
        "<a href='https://evil.com'>click&steal</a>",
        "&&&<><>\"\"'''",
        "Анон" * 500,  # 2000 chars
        "⚠️ 🔥 🪖 🐱 👑 🥼 🕶️ 🦺 👽 🎩 📦 🎭 🤡 " * 50,  # Multi-byte emojis
        "Special\x00Null\r\n\tControlChars",
        "Zero\u200bWidth\u200cJoiner\u200dTest",
        "RTL \u202e Override \u202c Attack",
    ]

    all_boards = [
        "b", "int", "a", "po", "vg", "news", "soc", "media"
    ]

    for adv_str in adversarial_inputs:
        for board in all_boards:
            # Simulate a post header with compact_post_icon + custom title
            compact_icon = "🪖 "
            custom_prefix = adv_str

            # Construct mock header string as format_header does:
            # custom_prefix = badge_emoji + compact_icon + debuff_icons + prefix_str
            header_text = f"{compact_icon}{custom_prefix} Пост №12345"

            # 1. Delivery manager wraps header in <i>{escape_html(header_text)}</i>
            escaped_header = escape_html(header_text)
            head_markup = f"<i>{escaped_header}</i>"

            # 2. Strict HTML / XML validity verification
            # In Telegram HTML, unescaped &, <, > break message delivery.
            # Wrapping in <root> and parsing with XML validates well-formedness.
            wrapped_xml = f"<root>{head_markup}</root>"
            try:
                # ET.fromstring will fail if there are unescaped HTML entities or unbalanced tags
                # Replace named HTML entities with numeric for basic XML parser
                xml_safe = (
                    wrapped_xml.replace("&quot;", "&#34;")
                    .replace("&amp;", "&#38;")
                    .replace("&lt;", "&#60;")
                    .replace("&gt;", "&#62;")
                )
                ET.fromstring(xml_safe)
            except Exception as e:
                pytest.fail(f"HTML escaping produced malformed markup for input {adv_str[:30]!r}: {e}")

            # 3. Verify Telegram limits
            # Telegram text limit is 4096, caption limit is 1024
            # When delivery_manager truncates:
            full_text = f"{head_markup}\n\nNormal post body"
            if len(full_text) > 4096:
                truncated_text = full_text[:4093] + "..."
                assert len(truncated_text) <= 4096


def test_stats_generator_text_report_adversarial():
    """
    Stress-test stats_generator._format_text_report with equipped sets,
    long names, and adversarial characters.
    """
    now = int(time.time())

    # Build active items with full riot police set
    riot_items = {
        "equipped_head": "hat_helmet",
        "hat_helmet_is_permanent": True,
        "equipped_feet": "feet_boots",
        "feet_boots_is_permanent": True,
    }

    card_data = stats_generator.UserStatsCardData(
        user_id=123456789,
        board_id="b",
        schizo_name="<script>alert(1)</script> Онотоле",
        role_name="Бог Шитпостинга",
        custom_prefix="👑 <b>VIP</b>",
        rank=1,
        total_users=1000,
        posts_count=99999,
        rx_received=50000,
        rx_given=40000,
        approval_pct=98.5,
        balance=1000000000.0,
        mutes_count=0,
        cringe_factor=0.0,
        chronotype="Сыч ночной",
        slang_comment="Убер-двачер легендарного ранга",
        avatar_file_id=None,
        active_items=riot_items,
    )

    report = stats_generator._format_text_report(card_data)
    assert "🎽 <b>Экипировка:</b>" in report
    assert "✨ <b>Сет:</b>" in report
    assert "🪖 " in report
    assert "Сет «Силовик ОМОНа»" in report


# =====================================================================
# 2. WORK ENGINE: ALL 16 SHIFTS & hat_helmet ZERO FINE PERK
# =====================================================================

def test_work_engine_16_vacancies_presence():
    """Verify all 16 vacancies exist, have valid configurations, and no zero division traps."""
    vacancies = work_engine.get_vacancies()
    assert len(vacancies) == 16, f"Expected exactly 16 vacancies, found {len(vacancies)}"

    expected_keys = [
        "bottles", "sweeper", "courier", "captcha", "spy", "factory",
        "it_freelance", "scam", "deputy", "escort_sugar", "crypto_cartel",
        "infogypsy_cult", "propaganda_troll", "abu_consigliere",
        "shadow_oligarch", "matrix_architect"
    ]
    for key in expected_keys:
        assert key in vacancies, f"Missing vacancy: {key}"
        v = vacancies[key]
        assert "title" in v
        assert "reward_range" in v
        assert len(v["reward_range"]) == 2
        assert v["reward_range"][0] > 0
        assert v["reward_range"][1] >= v["reward_range"][0]
        assert v["cooldown_sec"] > 0
        assert v["risk_pct"] >= 0.0
        assert v["penalty"] >= 0


def test_work_engine_hat_helmet_zero_fine_across_all_16_shifts():
    """
    CRITICAL EMPIRICAL TEST:
    For all 16 shifts, equipping hat_helmet MUST guarantee ZERO fines (is_success = True),
    even when random.random() returns worst-case 0.00001 (triggering 100% of risk rolls).
    """
    now = int(time.time())
    vacancies = work_engine.get_vacancies()

    # User with hat_helmet and enough shifts to qualify for all jobs (650 shifts)
    helmet_items = {
        "equipped_head": "hat_helmet",
        "hat_helmet_is_permanent": True,
        "work_shifts": 700,
        "work_cooldowns": {},
    }

    for job_id, v in vacancies.items():
        # Reset cooldown for this shift
        helmet_items["work_cooldowns"] = {}

        # Adversarial patch: random.random() = 0.0000001
        # Without helmet, this would ALWAYS trigger failure on any shift with risk_pct > 0
        with patch("random.random", return_value=0.0000001):
            success, reward, msg, drop = work_engine.execute_job_action(
                job_id=job_id,
                current_items=helmet_items,
            )

            assert success is True, (
                f"Shift {job_id} failed with hat_helmet equipped! msg: {msg}"
            )
            assert reward > 0, (
                f"Shift {job_id} returned zero or negative reward: {reward}"
            )
            assert "ШТРАФ" not in msg, (
                f"Shift {job_id} produced fine message despite hat_helmet: {msg}"
            )
            assert "0% штрафов" in msg, (
                f"Shift {job_id} did not display helmet perk note in message: {msg}"
            )


def test_work_engine_riot_police_set_zero_fine_across_all_16_shifts():
    """Test set_riot_police also gives 100% fine immunity across all 16 shifts."""
    now = int(time.time())
    vacancies = work_engine.get_vacancies()

    riot_items = {
        "equipped_head": "hat_helmet",
        "hat_helmet_expires": now + 7200,
        "equipped_feet": "feet_boots",
        "feet_boots_expires": now + 7200,
        "work_shifts": 700,
        "work_cooldowns": {},
    }

    for job_id in vacancies:
        riot_items["work_cooldowns"] = {}
        with patch("random.random", return_value=0.0000001):
            success, reward, msg, _ = work_engine.execute_job_action(
                job_id=job_id,
                current_items=riot_items,
            )
            assert success is True, f"Shift {job_id} failed with set_riot_police!"
            assert reward > 0
            assert "ШТРАФ" not in msg


def test_work_engine_division_by_zero_stress():
    """
    Stress-test work engine against division by zero with extreme boundary inputs:
    - passed time = 0, negative, or astronomical.
    - work_shifts = 0, negative.
    - reward_range edge cases.
    """
    now = int(time.time())

    boundary_cases = [
        {"work_shifts": 0, "work_cooldowns": {"bottles": now}},  # passed = 0
        {"work_shifts": -999, "work_cooldowns": {"bottles": now + 10000}},  # future
        {"work_shifts": 10**9, "work_cooldowns": {"bottles": 0}},  # max passed
    ]

    for b_case in boundary_cases:
        items = b_case.copy()
        try:
            work_engine.execute_job_action("bottles", items)
        except ZeroDivisionError:
            pytest.fail(f"ZeroDivisionError in execute_job_action with items {b_case}")
        except Exception:
            pass  # Normal rejection (e.g. cooldown) is expected, not ZeroDivisionError


# =====================================================================
# 3. COMBAT MODERATION ENGINE: HIGH VOLUME & STATISTICAL EVASION
# =====================================================================

def test_combat_duration_high_volume_mute_reductions():
    """
    Run 10,000 high volume executions of calculate_combat_duration_and_backfire:
    - 5,000 for 'shoot'
    - 5,000 for 'partyvan'
    Verify:
    1. Zero division by zero errors.
    2. Hat helmet gives exact 50% mute reduction (clamped >= 60s).
    3. Riot police set gives exact 70% mute reduction (clamped >= 60s).
    4. Expired helmet gives 0% reduction.
    """
    now = int(time.time())

    helmet_target = {
        "equipped_head": "hat_helmet",
        "hat_helmet_expires": now + 3600,
    }
    riot_target = {
        "equipped_head": "hat_helmet",
        "hat_helmet_expires": now + 3600,
        "equipped_feet": "feet_boots",
        "feet_boots_expires": now + 3600,
    }
    expired_target = {
        "equipped_head": "hat_helmet",
        "hat_helmet_expires": now - 3600,
    }

    # High volume loop
    for i in range(5000):
        attacker_id = 10000 + (i % 50)
        target_id = 20000 + (i % 50)
        target_posts = 300  # Full 1.0 multiplier

        # Base with no backfire forced
        with patch("random.random", return_value=0.99):  # No backfire
            # Shoot without gear -> 900s (if 0 prior attacks)
            dur_base, back_base, _ = combat_moderation_engine.calculate_combat_duration_and_backfire(
                attacker_id, target_id, "shoot", target_posts, target_items=None
            )
            assert dur_base in (900, 600, 300, 60)
            assert not back_base

            # Shoot with helmet -> 50% reduction
            dur_h, _, _ = combat_moderation_engine.calculate_combat_duration_and_backfire(
                attacker_id, target_id, "shoot", target_posts, target_items=helmet_target
            )
            expected_h = max(60, int(round(dur_base * 0.5)))
            assert dur_h == expected_h, f"Expected {expected_h}, got {dur_h} for base {dur_base}"

            # Shoot with riot set -> 70% reduction
            dur_r, _, _ = combat_moderation_engine.calculate_combat_duration_and_backfire(
                attacker_id, target_id, "shoot", target_posts, target_items=riot_target
            )
            expected_r = max(60, int(round(dur_base * 0.3)))
            assert dur_r == expected_r, f"Expected {expected_r}, got {dur_r} for base {dur_base}"

            # Shoot with expired gear -> 0% reduction
            dur_exp, _, _ = combat_moderation_engine.calculate_combat_duration_and_backfire(
                attacker_id, target_id, "shoot", target_posts, target_items=expired_target
            )
            assert dur_exp == dur_base

    # 5,000 iterations for partyvan
    for i in range(5000):
        attacker_id = 30000 + (i % 50)
        target_id = 40000 + (i % 50)
        target_posts = 300

        with patch("random.random", return_value=0.99):
            dur_pv_base, _, _ = combat_moderation_engine.calculate_combat_duration_and_backfire(
                attacker_id, target_id, "partyvan", target_posts, target_items=None
            )
            assert dur_pv_base in (10800, 5400, 2700, 1200)

            dur_pv_r, _, _ = combat_moderation_engine.calculate_combat_duration_and_backfire(
                attacker_id, target_id, "partyvan", target_posts, target_items=riot_target
            )
            expected_pv_r = max(60, int(round(dur_pv_base * 0.3)))
            assert dur_pv_r == expected_pv_r


def test_combat_evasion_statistical_validation():
    """
    Statistical validation of feet_sneakers evasion (30%) and body_cloak stealth (15%)
    over 10,000 iterations using binomial confidence intervals.
    """
    now = int(time.time())
    rng = random.Random(42)

    sneakers_items = {
        "equipped_feet": "feet_sneakers",
        "feet_sneakers_is_permanent": True,
    }
    stats = wardrobe_engine.get_wardrobe_total_stats(sneakers_items, current_time=now)
    evasion_chance = stats["evasion_chance"]
    assert evasion_chance == 0.30

    # 10,000 evasion rolls
    N = 10000
    evasions = 0
    for _ in range(N):
        if rng.random() < evasion_chance:
            evasions += 1

    # Standard error = sqrt(p * (1 - p) / N)
    # For p = 0.30, N = 10000: SE = sqrt(0.21 / 10000) = 0.00458
    # 99.9% CI is roughly 3.3 * SE ~= 0.015 -> [0.285, 0.315]
    rate = evasions / N
    assert 0.285 <= rate <= 0.315, (
        f"Empirical evasion rate {rate:.4f} deviated from 0.30 (evasions: {evasions}/{N})"
    )

    # Expired sneakers MUST give exactly 0% evasion
    expired_sneakers = {
        "equipped_feet": "feet_sneakers",
        "feet_sneakers_expires": now - 100,
    }
    stats_exp = wardrobe_engine.get_wardrobe_total_stats(expired_sneakers, current_time=now)
    assert stats_exp["evasion_chance"] == 0.0

    # Test body_cloak stealth (15%)
    cloak_stealth_chance = 0.15
    stealths = 0
    for _ in range(N):
        if rng.random() < cloak_stealth_chance:
            stealths += 1
    # For p = 0.15, SE = sqrt(0.1275 / 10000) = 0.00357
    # 99.9% CI: [0.138, 0.162]
    rate_cloak = stealths / N
    assert 0.138 <= rate_cloak <= 0.162, (
        f"Empirical cloak stealth rate {rate_cloak:.4f} deviated from 0.15"
    )


def test_combat_history_cleaner_under_rapid_load():
    """Verify clean_combat_history handles thousands of entries without crashing or mutating errors."""
    combat_moderation_engine._ATTACKER_COMBAT_HISTORY.clear()
    combat_moderation_engine._TARGET_PAIR_LAST_ATTACK.clear()

    now = time.time()
    # Add 5,000 history entries
    for i in range(5000):
        attacker = 1000 + (i % 100)
        target = 2000 + (i % 100)
        ts = now - (i * 20)  # spans back 100,000 seconds
        combat_moderation_engine._ATTACKER_COMBAT_HISTORY[attacker].append((ts, target, "shoot"))
        combat_moderation_engine._TARGET_PAIR_LAST_ATTACK[(attacker, target)] = ts

    # Execute cleaner multiple times rapidly
    for _ in range(10):
        combat_moderation_engine.clean_combat_history()

    # Verify no entries older than 24h (86400s) remain
    cutoff = now - 86400.0
    for uid, history in combat_moderation_engine._ATTACKER_COMBAT_HISTORY.items():
        for ts, _, _ in history:
            assert ts > cutoff, f"Found stale record with ts {ts} < {cutoff}"
